### ISSUE TITLE
White background and previews?

### ISSUE THREAD

**Issue by anderspitman** [Anuken/PixelEditor#1]
Hi @Anuken ,

I just downloaded Novix and it looks great. Excellent work. I was just about to hack together a cursor-based pixel editor for mobile, but I think I might be able to get away with using this instead.

Do you have any plans to having a white canvas and/or a way to preview your image?

**Comment by Anuken** [comment]
[See README.](https://github.com/Anuken/Novix/blob/master/README.md)
