### ISSUE TITLE
Incompatible uCore

### ISSUE THREAD

**Issue by electronstudio** [Anuken/PixelEditor#3]
I tried compiling using the supplied uCore.jar and got a lot of errors.
So I built a new uCore from latest sources and still got a lot of errors.
So I built a uCore from the uCore sources that were checked in on same day as Novix sources.  I got fewer errors, I think this is pretty close, but still not right.

If there are certain versions of Novix / uCore that are more stable that I should be using please let me know!

If you're wondering why I'm trying to build Novix, it's because I like the Android version but I would like to use it on my iPad.

**Comment by Anuken** [comment]
[See README.](https://github.com/Anuken/Novix/blob/master/README.md)
